FactoryGirl.create(:category, name: "Technology")
FactoryGirl.create(:category, name: "Business & Finance")
FactoryGirl.create(:category, name: "News & Politics")
FactoryGirl.create(:category, name: "Programming")
FactoryGirl.create(:category, name: "Comics")
FactoryGirl.create(:category, name: "YouTube Channels")
FactoryGirl.create(:category, name: "Sports")
FactoryGirl.create(:category, name: "Fun")
FactoryGirl.create(:category, name: "Movies")
FactoryGirl.create(:category, name: "Gaming")
FactoryGirl.create(:category, name: "DIY")
FactoryGirl.create(:category, name: "Books")
FactoryGirl.create(:category, name: "Design & Inspiration")
FactoryGirl.create(:category, name: "Architecture & Interior")
FactoryGirl.create(:category, name: "Art & Culture")
FactoryGirl.create(:category, name: "Photography")
FactoryGirl.create(:category, name: "Knowledge")
FactoryGirl.create(:category, name: "Thinkers")
FactoryGirl.create(:category, name: "Food")
FactoryGirl.create(:category, name: "Music")
FactoryGirl.create(:category, name: "Podcasts")
FactoryGirl.create(:category, name: "Lifestyle")
FactoryGirl.create(:category, name: "Fashion")
FactoryGirl.create(:category, name: "Health & Life")
FactoryGirl.create(:category, name: "Celebrities")
FactoryGirl.create(:category, name: "Auto")
FactoryGirl.create(:category, name: "Tutorials & Howtos")
FactoryGirl.create(:category, name: "Travel")

FactoryGirl.create(:user, email: "user@example.com", username: "user")
FactoryGirl.create(:user, full_name: "Brian Wilson", email: "brian@gmail.com", username: "brian")
FactoryGirl.create(:user, full_name: "Peter Moore", email: "peter@gmail.com", username: "peter")
FactoryGirl.create(:user, full_name: "Ramilia Nigmatullina", email: "ramilia@gmail.com", username: "ramilia")


FactoryGirl.create(:blog, name: "Film School Rejects", description: "A Website About Movies", user_id: 2, category_id: 9)
FactoryGirl.create(:blog, name: "Atlas Obscura", description: "New wonders and curiosities added to the Atlas", user_id: 3, category_id: 28)
FactoryGirl.create(:blog, name: "Frugal Traveler", description: "A New York Times Blog", user_id: 4, category_id: 28)

FactoryGirl.create(:subscription, blog_id: 1, user_id: 3)
FactoryGirl.create(:subscription, blog_id: 2, user_id: 2)
FactoryGirl.create(:subscription, blog_id: 2, user_id: 1)
FactoryGirl.create(:subscription, blog_id: 1, user_id: 4)
FactoryGirl.create(:subscription, blog_id: 2, user_id: 4)

FactoryGirl.create(:post, title: "Harry Potter and the Philosopher's Stone", blog_id: 1, user_id: 2)
FactoryGirl.create(:post, title: "Harry Potter and the Chamber of Secrets", blog_id: 1, user_id: 2)
FactoryGirl.create(:post, title: "Harry Potter and the Prisoner of Azkaban", blog_id: 1, user_id: 2)
FactoryGirl.create(:post, title: "9 Incredible Meteorite Craters That Look Straight Out of 'Deep Impact'", blog_id: 2, user_id: 3)
FactoryGirl.create(:post, title: "Spitzhäuschen in Bernkastel-Kues, Germany", blog_id: 2, user_id: 3)
FactoryGirl.create(:post, title: "A Move for the Frugal Traveler", blog_id: 3, user_id: 4)
FactoryGirl.create(:post, title: "Is New York’s New Bike-Sharing Program Good for Tourists?", blog_id: 3, user_id: 4)

FactoryGirl.create(:post, title: "Now You See Me", blog_id: 1, user_id: 2)
FactoryGirl.create(:post, title: "Inception", blog_id: 1, user_id: 2)
FactoryGirl.create(:post, title: "Good Will Hunting", blog_id: 1, user_id: 2)
FactoryGirl.create(:post, title: "The Lord of the Rings", blog_id: 1, user_id: 2)
FactoryGirl.create(:post, title: "The Departed", blog_id: 1, user_id: 2)
FactoryGirl.create(:post, title: "Sherlock Holmes", blog_id: 1, user_id: 2)
FactoryGirl.create(:post, title: "USA", blog_id: 2, user_id: 3)

FactoryGirl.create(:comment, user_id: 2, post_id: 4)
FactoryGirl.create(:comment, user_id: 2, post_id: 5)
FactoryGirl.create(:comment, user_id: 2, post_id: 5)
FactoryGirl.create(:comment, user_id: 3, post_id: 1)
FactoryGirl.create(:comment, user_id: 3, post_id: 1)
FactoryGirl.create(:comment, user_id: 3, post_id: 2)
FactoryGirl.create(:comment, user_id: 3, post_id: 4)

# FactoryGirl.create(:tag, name: "harrypotter", post_id: 1)
# FactoryGirl.create(:tag, name: "harrypotter", post_id: 2)
# FactoryGirl.create(:tag, name: "harrypotter", post_id: 3)
# FactoryGirl.create(:tag, name: "movie", post_id: 1)
# FactoryGirl.create(:tag, name: "movie", post_id: 2)
# FactoryGirl.create(:tag, name: "movie", post_id: 3)
# FactoryGirl.create(:tag, name: "usa", post_id: 4)
# FactoryGirl.create(:tag, name: "travel", post_id: 5)
