defaults: &defaults
  adapter: postgresql
  encoding: unicode
  min_messages: warning
  user: postgres
  password: postgres
  host: localhost
  timeout: 5000
  pool: 5

development:
  database: blog-engine_dev
  <<: *defaults

test:
  database: blog-engine_test
  <<: *defaults

production: &deploy
  <<: *defaults
