FactoryGirl.create(:category, name: "Technology")
FactoryGirl.create(:category, name: "Business & Finance")
FactoryGirl.create(:category, name: "News & Politics")
FactoryGirl.create(:category, name: "Programming")
FactoryGirl.create(:category, name: "Comics")
FactoryGirl.create(:category, name: "YouTube Channels")
FactoryGirl.create(:category, name: "Sports")
FactoryGirl.create(:category, name: "Fun")
FactoryGirl.create(:category, name: "Movies")
FactoryGirl.create(:category, name: "Gaming")
FactoryGirl.create(:category, name: "DIY")
FactoryGirl.create(:category, name: "Books")
FactoryGirl.create(:category, name: "Design & Inspiration")
FactoryGirl.create(:category, name: "Architecture & Interior")
FactoryGirl.create(:category, name: "Art & Culture")
FactoryGirl.create(:category, name: "Photography")
FactoryGirl.create(:category, name: "Knowledge")
FactoryGirl.create(:category, name: "Thinkers")
FactoryGirl.create(:category, name: "Food")
FactoryGirl.create(:category, name: "Music")
FactoryGirl.create(:category, name: "Podcasts")
FactoryGirl.create(:category, name: "Lifestyle")
FactoryGirl.create(:category, name: "Fashion")
FactoryGirl.create(:category, name: "Health & Life")
FactoryGirl.create(:category, name: "Celebrities")
FactoryGirl.create(:category, name: "Auto")
FactoryGirl.create(:category, name: "Tutorials & Howtos")
FactoryGirl.create(:category, name: "Travel")
