Category.create(name: "Technology")
Category.create(name: "Business & Finance")
Category.create(name: "News & Politics")
Category.create(name: "Programming")
Category.create(name: "Comics")
Category.create(name: "YouTube Channels")
Category.create(name: "Sports")
Category.create(name: "Fun")
Category.create(name: "Movies")
Category.create(name: "Gaming")
Category.create(name: "DIY")
Category.create(name: "Books")
Category.create(name: "Design & Inspiration")
Category.create(name: "Architecture & Interior")
Category.create(name: "Art & Culture")
Category.create(name: "Photography")
Category.create(name: "Knowledge")
Category.create(name: "Thinkers")
Category.create(name: "Food")
Category.create(name: "Music")
Category.create(name: "Podcasts")
Category.create(name: "Lifestyle")
Category.create(name: "Fashion")
Category.create(name: "Health & Life")
Category.create(name: "Celebrities")
Category.create(name: "Auto")
Category.create(name: "Tutorials & Howtos")
Category.create(name: "Travel")
